name: Node.js CI

on:
  push:
    branches: [ "main", "run-tests-in-ci" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./firestarter-nextjs
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test --ci
