name: Tests (nextjs)

on:
  push:

defaults:
  run:
    working-directory: nextjs

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: firestarter-nextjs
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test:ci
