name: Tests (nextjs)

on:
  push:

defaults:
  run:
    working-directory: nextjs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test:ci
